package com.gasq.bdp.logn.model;

import java.util.Date;

public class Jobconfig extends BaseBean{
	private static final long serialVersionUID = 1L;
	private String createUser;

	private Date updateTime;

	private Date createTime;
	 private Integer index;   
	public String getCreateUser() {
		return createUser;
	}
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}
	public Date getUpdateTime() {
		return updateTime;
	}
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Integer getIndex() {
		return index;
	}
	public void setIndex(Integer index) {
		this.index = index;
	}
	private long cid;
	public long getCid() {
		return cid;
	}
	public void setCid(long cid) {
		this.cid = cid;
	}
	private int status;
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	private int startIndex;
	private int endIndex;
	public int getStartIndex() {
		return startIndex;
	}
	public void setStartIndex(int startIndex) {
		this.startIndex = startIndex;
	}
	public int getEndIndex() {
		return endIndex;
	}
	public void setEndIndex(int endIndex) {
		this.endIndex = endIndex;
	}
	public int getPage() {
		return page;
	}
	public void setPage(int page) {
		this.page = page;
	}
	public int getRows() {
		return rows;
	}
	public void setRows(int rows) {
		this.rows = rows;
	}
	private int page=1;
	private int rows=10;



	/**
	 * 是否分页 默认为不分页
	 */
	/*private boolean isLimit = false;*/
	/**
	 * 分页页码 默认为0
	 */
/*	private int pageSize = 0;*/
	/**
	 * 分页数量 默认1000条
	 */
/*	private int pageNum = 1000;*/
	/**
	 * 排序字段 目前只是正序
	 */
/*	private String orderbyColumn;*/
	/**
	 * 目标表的主键
	 */
/*	private Map<String,Object> keys;*/
	/**
	 * 主键对应的column属性  eg:字段类型 是否为空 是不是主键...
	 */
/*	private Map<String,Object> keysValue;*/
	/**
	 * 是否更新  默认为不更新：只插入数据
	 */
/*	private boolean isUpdate = false;*/
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobconfig.id
     *
     * @mbg.generated Tue Jul 04 17:14:11 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobconfig.targettablename
     *
     * @mbg.generated Tue Jul 04 17:14:11 CST 2017
     */
    private String targetTableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobconfig.sourcedatabase
     *
     * @mbg.generated Tue Jul 04 17:14:11 CST 2017
     */
    private String sourceDataBase= InitProperties.DB_DEFAULT;
    private String sourceDataBases;
    public String getSourceDataBases() {
		return sourceDataBases;
	}
	public void setSourceDataBases(String sourceDataBases) {
		this.sourceDataBases = sourceDataBases;
	}
	private String targetDataBases;

    public String getTargetDataBases() {
		return targetDataBases;
	}
	public void setTargetDataBases(String targetDataBases) {
		this.targetDataBases = targetDataBases;
	}
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobconfig.targetdatabase
     *
     * @mbg.generated Tue Jul 04 17:14:11 CST 2017
     */
    private String targetDataBase= InitProperties.DB_DEFAULT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobconfig.beforedb
     *
     * @mbg.generated Tue Jul 04 17:14:11 CST 2017
     */
    private String beforeDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobconfig.afterdb
     *
     * @mbg.generated Tue Jul 04 17:14:11 CST 2017
     */
    private Long id1;
    public Long getId1() {
		return id1;
	}
	public void setId1(Long id1) {
		this.id1 = id1;
	}
	private String afterDb;

    public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getTargetTableName() {
		return targetTableName;
	}
	public void setTargetTableName(String targetTableName) {
		this.targetTableName = targetTableName;
	}
	public String getSourceDataBase() {
		return sourceDataBase;
	}
	public void setSourceDataBase(String sourceDataBase) {
		this.sourceDataBase = sourceDataBase;
	}
	public String getTargetDataBase() {
		return targetDataBase;
	}
	public void setTargetDataBase(String targetDataBase) {
		this.targetDataBase = targetDataBase;
	}
	public String getBeforeDb() {
		return beforeDb;
	}
	public void setBeforeDb(String beforeDb) {
		this.beforeDb = beforeDb;
	}
	public String getAfterDb() {
		return afterDb;
	}
	public void setAfterDb(String afterDb) {
		this.afterDb = afterDb;
	}
	public String getBeforeSql() {
		return beforeSql;
	}
	public void setBeforeSql(String beforeSql) {
		this.beforeSql = beforeSql;
	}
	public String getAfterSql() {
		return afterSql;
	}
	public void setAfterSql(String afterSql) {
		this.afterSql = afterSql;
	}
	public String getSql() {
		return sql;
	}
	public void setSql(String sql) {
		this.sql = sql;
	}
	private String beforeSql;
    private String afterSql;
    private String sql;
    private String sql1;
    private String targetTableName1;
    private String sourceDataBase1;
    private String targetDataBase1;
    private String beforeDb1;
    private String afterDb1;
    private String beforeSql1;
    private String afterSql1;
    private String sql2;
    private String targetTableName2;
    private String sourceDataBase2;
    private String targetDataBase2;
    private String beforeDb2;
    private String afterDb2;
    private String beforeSql2;
    private String afterSql2;
	public String getSql1() {
		return sql1;
	}
	public void setSql1(String sql1) {
		this.sql1 = sql1;
	}
	public String getTargetTableName1() {
		return targetTableName1;
	}
	public void setTargetTableName1(String targetTableName1) {
		this.targetTableName1 = targetTableName1;
	}
	public String getSourceDataBase1() {
		return sourceDataBase1;
	}
	public void setSourceDataBase1(String sourceDataBase1) {
		this.sourceDataBase1 = sourceDataBase1;
	}
	public String getTargetDataBase1() {
		return targetDataBase1;
	}
	public void setTargetDataBase1(String targetDataBase1) {
		this.targetDataBase1 = targetDataBase1;
	}
	public String getBeforeDb1() {
		return beforeDb1;
	}
	public void setBeforeDb1(String beforeDb1) {
		this.beforeDb1 = beforeDb1;
	}
	public String getAfterDb1() {
		return afterDb1;
	}
	public void setAfterDb1(String afterDb1) {
		this.afterDb1 = afterDb1;
	}
	public String getBeforeSql1() {
		return beforeSql1;
	}
	public void setBeforeSql1(String beforeSql1) {
		this.beforeSql1 = beforeSql1;
	}
	public String getAfterSql1() {
		return afterSql1;
	}
	public void setAfterSql1(String afterSql1) {
		this.afterSql1 = afterSql1;
	}
	public String getSql2() {
		return sql2;
	}
	public void setSql2(String sql2) {
		this.sql2 = sql2;
	}
	public String getTargetTableName2() {
		return targetTableName2;
	}
	public void setTargetTableName2(String targetTableName2) {
		this.targetTableName2 = targetTableName2;
	}
	public String getSourceDataBase2() {
		return sourceDataBase2;
	}
	public void setSourceDataBase2(String sourceDataBase2) {
		this.sourceDataBase2 = sourceDataBase2;
	}
	public String getTargetDataBase2() {
		return targetDataBase2;
	}
	public void setTargetDataBase2(String targetDataBase2) {
		this.targetDataBase2 = targetDataBase2;
	}
	public String getBeforeDb2() {
		return beforeDb2;
	}
	public void setBeforeDb2(String beforeDb2) {
		this.beforeDb2 = beforeDb2;
	}
	public String getAfterDb2() {
		return afterDb2;
	}
	public void setAfterDb2(String afterDb2) {
		this.afterDb2 = afterDb2;
	}
	public String getBeforeSql2() {
		return beforeSql2;
	}
	public void setBeforeSql2(String beforeSql2) {
		this.beforeSql2 = beforeSql2;
	}
	public String getAfterSql2() {
		return afterSql2;
	}
	public void setAfterSql2(String afterSql2) {
		this.afterSql2 = afterSql2;
	}
}