package com.gasq.bdp.logn.model;

import java.util.Date;
import java.util.List;

public class Scheduleconfig {
	private List<Jobconfig> list;
	
	private String remark;

	private String createUser;

	private Date updateTime;

	private Date createTime;

	private Boolean status;

	private String cron1;
	private String name1;
	private String group1;
	private Long id2;

	private String cron2;
	private String name2;
	private String group2;

	private int page=1;
	private int rows=10;
	private String crons;
	private String names;
	private String groups;
	private int startIndex;
	private int endIndex;
	public int getStartIndex() {
		return startIndex;
	}

	public void setStartIndex(int startIndex) {
		this.startIndex = startIndex;
	}

	public int getEndIndex() {
		return endIndex;
	}

	public void setEndIndex(int endIndex) {
		this.endIndex = endIndex;
	}

	public String getCrons() {
		return crons;
	}

	public void setCrons(String crons) {
		this.crons = crons;
	}

	public String getNames() {
		return names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	public String getGroups() {
		return groups;
	}

	public void setGroups(String groups) {
		this.groups = groups;
	}

	public int getPage() {
		return page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getRows() {
		return rows;
	}

	public void setRows(int rows) {
		this.rows = rows;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column scheduleconfig.id
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column scheduleconfig.cron
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	private String cron;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column scheduleconfig.name
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column scheduleconfig.group
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	private String group;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column scheduleconfig.id
	 * @return  the value of scheduleconfig.id
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column scheduleconfig.id
	 * @param id  the value for scheduleconfig.id
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column scheduleconfig.cron
	 * @return  the value of scheduleconfig.cron
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public String getCron() {
		return cron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column scheduleconfig.cron
	 * @param cron  the value for scheduleconfig.cron
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public void setCron(String cron) {
		this.cron = cron;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column scheduleconfig.name
	 * @return  the value of scheduleconfig.name
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column scheduleconfig.name
	 * @param name  the value for scheduleconfig.name
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column scheduleconfig.group
	 * @return  the value of scheduleconfig.group
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public String getGroup() {
		return group;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column scheduleconfig.group
	 * @param group  the value for scheduleconfig.group
	 * @mbg.generated  Sat Jul 01 20:14:16 CST 2017
	 */
	public void setGroup(String group) {
		this.group = group;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public List<Jobconfig> getList() {
		return list;
	}

	public void setList(List<Jobconfig> list) {
		this.list = list;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getCron1() {
		return cron1;
	}

	public void setCron1(String cron1) {
		this.cron1 = cron1;
	}

	public String getName1() {
		return name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	public String getGroup1() {
		return group1;
	}

	public void setGroup1(String group1) {
		this.group1 = group1;
	}

	public Long getId2() {
		return id2;
	}

	public void setId2(Long id2) {
		this.id2 = id2;
	}

	public String getCron2() {
		return cron2;
	}

	public void setCron2(String cron2) {
		this.cron2 = cron2;
	}

	public String getName2() {
		return name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public String getGroup2() {
		return group2;
	}

	public void setGroup2(String group2) {
		this.group2 = group2;
	}
	
}